export default {
  info: [
    { type: 'input', name: 'name', title: '姓名' },
    { type: 'input', name: 'gender', title: '性别' },
    { type: 'input', name: 'id', title: '学号' },
    { type: 'input', name: 'academy', title: '学院' },
    { type: 'input', name: 'phone', title: '联系电话' },
    { type: 'input', name: 'arrive_time', title: '预计抵达时间' },
    { type: 'input', name: 'transportation', title: '交通工具' },
    { type: 'input', name: 'dom', title: '寝室楼 - 寝室号' },
    { type: 'input', name: 'class', title: '班号' },
    { type: 'switch', name: 'infect', title: '有无感染新冠病毒史' },
    { type: 'switch', name: 'ok', title: '是否还在感染中' },
    { type: 'switch', name: 'contact', title: '有无病患/疑似病患接触史' },
    { type: 'switch', name: 'symptom', title: '有无头疼、发热、等的症状' },
  ],
  personal: [
    { type: 'input', name: 'degree', title: '今日体温' },
    { type: 'switch', name: 'symptom', title: '有无头疼、发热、等的症状' },
    { type: 'text', text: '若有上述症状请填下面的内容' },
    { type: 'switch', name: 'out', title: '是否有外出' },
    { type: 'switch', name: 'contact', title: '是否与病患接触' },
    { type: 'switch', name: 'doctor', title: '是否就医' },
    { type: 'switch', name: 'infect', title: '是否确定感染' },
  ],
  room: [
    { type: 'input', name: 'dom', title: '公寓楼' },
    { type: 'input', name: 'id', title: '寝室号' },
    { type: 'switch', name: 'refresh', title: '是否定时通风' },
    { type: 'switch', name: 'symptom', title: '是否有头疼、发热等症状' },
    { type: 'text', text: '若有上述症状请填下面的内容' },
    { type: 'input', name: 'count', title: '发热症状人数' },
    { type: 'switch', name: 'out', title: '是否有外出' },
    { type: 'switch', name: 'contact', title: '是否与病患接触' },
    { type: 'switch', name: 'doctor', title: '是否就医' },
    { type: 'switch', name: 'infect', title: '是否确定感染' },
  ],
};
